package com.qinkai.dao;

import com.qinkai.pojo.Cat;
import java.util.List;

public interface CatMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cat
     *
     * @mbggenerated Thu Jan 28 20:54:36 CST 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cat
     *
     * @mbggenerated Thu Jan 28 20:54:36 CST 2021
     */
    int insert(Cat record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cat
     *
     * @mbggenerated Thu Jan 28 20:54:36 CST 2021
     */
    Cat selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cat
     *
     * @mbggenerated Thu Jan 28 20:54:36 CST 2021
     */
    List<Cat> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cat
     *
     * @mbggenerated Thu Jan 28 20:54:36 CST 2021
     */
    int updateByPrimaryKey(Cat record);
}