package com.qinkai.pojo;

public class Cat {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cat.id
     *
     * @mbggenerated Thu Jan 28 20:54:36 CST 2021
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cat.name
     *
     * @mbggenerated Thu Jan 28 20:54:36 CST 2021
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cat.age
     *
     * @mbggenerated Thu Jan 28 20:54:36 CST 2021
     */
    private Integer age;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cat.id
     *
     * @return the value of t_cat.id
     *
     * @mbggenerated Thu Jan 28 20:54:36 CST 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cat.id
     *
     * @param id the value for t_cat.id
     *
     * @mbggenerated Thu Jan 28 20:54:36 CST 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cat.name
     *
     * @return the value of t_cat.name
     *
     * @mbggenerated Thu Jan 28 20:54:36 CST 2021
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cat.name
     *
     * @param name the value for t_cat.name
     *
     * @mbggenerated Thu Jan 28 20:54:36 CST 2021
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cat.age
     *
     * @return the value of t_cat.age
     *
     * @mbggenerated Thu Jan 28 20:54:36 CST 2021
     */
    public Integer getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cat.age
     *
     * @param age the value for t_cat.age
     *
     * @mbggenerated Thu Jan 28 20:54:36 CST 2021
     */
    public void setAge(Integer age) {
        this.age = age;
    }
}